// Auto-generated IPC types
// Do not edit this file manually - run 'tronbun generate-types' to regenerate
// Generated handlers for MainWindow
export interface MainWindowHandlers {
  setOpacity: (data: number) => Promise<void>;
  setResizable: (data: boolean) => Promise<void>;
  setPosition: (data: number) => Promise<void>;
  setAlwaysOnTop: (data: boolean) => Promise<void>;
  setTransparent: (data: void) => Promise<void>;
  setOpaque: (data: void) => Promise<void>;
  enableBlur: (data: void) => Promise<void>;
  removeDecorations: (data: void) => Promise<void>;
  centerWindow: (data: void) => Promise<void>;
  minimizeWindow: (data: void) => Promise<void>;
  maximizeWindow: (data: void) => Promise<void>;
  restoreWindow: (data: void) => Promise<void>;
  setSize: (data: number) => Promise<void>;
  setTitle: (data: string) => Promise<void>;
  addDecorations: (data: void) => Promise<void>;
  hideWindow: (data: void) => Promise<void>;
  showWindow: (data: void) => Promise<void>;
  openFileDialog: (data: { title?: string; multiple?: boolean; filters?: Array<{ name: string; extensions: string[] }> }) => Promise<string[] | any>;
  saveFileDialog: (data: { title?: string; defaultName?: string; filters?: Array<{ name: string; extensions: string[] }> }) => Promise<string | any>;
  openFolderDialog: (data: { title?: string }) => Promise<string | any>;
  showInfoDialog: (data: { message: string; title?: string }) => Promise<void>;
  showWarningDialog: (data: { message: string; title?: string }) => Promise<void>;
  showErrorDialog: (data: { message: string; title?: string }) => Promise<void>;
  confirmDialog: (data: { message: string; title?: string }) => Promise<boolean>;
  messageBoxDialog: (data: { title?: string; message: string; detail?: string; type?: "info" | "warning" | "error" | "question"; buttons?: "ok" | "okCancel" | "yesNo" | "yesNoCancel" }) => Promise<string>;
  setDefaultMenu: (data: void) => Promise<void>;
  removeMenu: (data: void) => Promise<void>;
  resetCustomMenu: (data: void) => Promise<void>;
  setMenuItemEnabled: (data: { itemId: string; enabled: boolean }) => Promise<void>;
  setMenuItemChecked: (data: { itemId: string; checked: boolean }) => Promise<void>;
  showNotification: (data: { title: string; body?: string }) => Promise<string>;
  requestNotificationPermission: (data: void) => Promise<string>;
}


declare global {
  interface Window {
    test_options: MainWindowHandlers;
  }
}
