// Auto-generated IPC types
// Do not edit this file manually - run 'tronbun generate-types' to regenerate

// Generated handlers for MainWindow
export interface MainWindowHandlers {
  setOpacity: (data: number) => Promise<void>;
  setResizable: (data: boolean) => Promise<void>;
  setPosition: (data: number) => Promise<void>;
  setAlwaysOnTop: (data: boolean) => Promise<void>;
  setTransparent: (data: void) => Promise<void>;
  setOpaque: (data: void) => Promise<void>;
  enableBlur: (data: void) => Promise<void>;
  removeDecorations: (data: void) => Promise<void>;
  centerWindow: (data: void) => Promise<void>;
  minimizeWindow: (data: void) => Promise<void>;
  maximizeWindow: (data: void) => Promise<void>;
  restoreWindow: (data: void) => Promise<void>;
  setSize: (data: number) => Promise<void>;
  setTitle: (data: string) => Promise<void>;
  addDecorations: (data: void) => Promise<void>;
  hideWindow: (data: void) => Promise<void>;
  showWindow: (data: void) => Promise<void>;
}


declare global {
  interface Window {
    test_options: MainWindowHandlers;
  }
}
