import { writeFileSync } from "fs";
import { join, dirname, relative } from "path";
import type { TronbunConfig } from "../types.js";
import * as ts from "typescript";

interface HandlerInfo {
  methodName: string;
  handlerName: string;
  hasResponseHandler?: boolean;
  parameterType: string;
  returnType: string;
}

interface WindowMetadata {
  name: string;
  sourceFile: string;
  className: string;
  handlers: HandlerInfo[];
}

// Built-in TypeScript types that don't need to be extracted
const BUILTIN_TYPES = new Set([
  'string', 'number', 'boolean', 'void', 'any', 'unknown', 'never', 'null', 'undefined',
  'object', 'symbol', 'bigint', 'Date', 'Error', 'RegExp', 'Array', 'Map', 'Set',
  'Promise', 'Record', 'Partial', 'Required', 'Readonly', 'Pick', 'Omit', 'Exclude',
  'Extract', 'NonNullable', 'Parameters', 'ReturnType', 'InstanceType'
]);

export class GenerateTypesCommand {
  static async generateTypes(config: TronbunConfig, projectRoot: string): Promise<void> {
    console.log("🔧 Generating IPC types...");

    const configPath = ts.findConfigFile(projectRoot, ts.sys.fileExists, 'tsconfig.json');
    
    if (!configPath) {
      console.error("❌ Could not find tsconfig.json");
      return;
    }

    try {
      const { config: tsConfig } = ts.readConfigFile(configPath, ts.sys.readFile);
      const { options, fileNames } = ts.parseJsonConfigFileContent(
        tsConfig,
        ts.sys,
        dirname(configPath)
      );

      const program = ts.createProgram(fileNames, {
        ...options,
        experimentalDecorators: true,
        emitDecoratorMetadata: true,
      });

      const metadata = extractWindowsFromProgram(program, projectRoot);

      if (metadata.length === 0) {
        console.log("⚠️  No window classes with @windowName decorators found.");
        return;
      }

      // Collect all referenced types from handlers
      const referencedTypes = new Set<string>();
      for (const window of metadata) {
        for (const handler of window.handlers) {
          collectTypeReferences(handler.parameterType, referencedTypes);
          collectTypeReferences(handler.returnType, referencedTypes);
        }
      }

      // Extract interface definitions for referenced types
      const typeDefinitionsMap = extractInterfaceDefinitions(program, projectRoot, referencedTypes);

      const typesPath = join(projectRoot, "src", "ipc-types.ts");

      let typeDefinitions = `// Auto-generated IPC types
// Do not edit this file manually - run 'tronbun generate-types' to regenerate
`;

      // Add extracted interface definitions first
      if (typeDefinitionsMap.size > 0) {
        typeDefinitions += `\n// Extracted type definitions\n`;
        for (const [typeName, typeDef] of typeDefinitionsMap) {
          typeDefinitions += `${typeDef}\n\n`;
        }
      }

      // Generate specific handler interfaces for each window
      for (const window of metadata) {
        if (window.handlers.length > 0) {
          typeDefinitions += `// Generated handlers for ${window.className}
export interface ${window.className}Handlers {
`;
          for (const handler of window.handlers) {
            typeDefinitions += `  ${handler.handlerName}: (data: ${handler.parameterType}) => Promise<${handler.returnType}>;\n`;
          }
          typeDefinitions += `}\n\n`;
        }
      }

      typeDefinitions += `
declare global {
  interface Window {
`;

      for (const window of metadata) {
        if (window.handlers.length > 0) {
          typeDefinitions += `    ${window.name}: ${window.className}Handlers;\n`;
        }
      }

      typeDefinitions += `  }
}
`;

      writeFileSync(typesPath, typeDefinitions);

      console.log(`✅ Generated types for ${metadata.length} window(s)`);
      console.log(`📁 Generated file: ${typesPath}`);
      
      // Log discovered windows
      for (const window of metadata) {
        console.log(`   • ${window.name} (${window.className})`);
      }

    } catch (error) {
      console.error("❌ Error generating types:", error);
      throw error;
    }
  }
}

function extractWindowsFromProgram(program: ts.Program, projectRoot: string): WindowMetadata[] {
  const metadata: WindowMetadata[] = [];

  const sourceFiles = program.getSourceFiles().filter(
    file => !file.fileName.includes('node_modules') && 
            !file.fileName.includes('.d.ts') &&
            file.fileName.includes(projectRoot)
  );

  console.log(`📂 Processing ${sourceFiles.length} source files...`);

  for (const sourceFile of sourceFiles) {
    const windowsInFile = extractWindowsFromSourceFile(sourceFile);
    metadata.push(...windowsInFile);
  }

  return metadata;
}

function extractWindowsFromSourceFile(sourceFile: ts.SourceFile): WindowMetadata[] {
  const windows: WindowMetadata[] = [];

  function visit(node: ts.Node) {
    if (ts.isClassDeclaration(node)) {
      const windowName = extractWindowNameFromClass(node);
      if (windowName) {
        const handlers = extractHandlersFromClass(node);
        windows.push({ 
          name: windowName, 
          sourceFile: sourceFile.fileName, 
          className: node.name?.text || 'Unknown',
          handlers
        });
      }
    }
    ts.forEachChild(node, visit);
  }

  visit(sourceFile);
  return windows;
}

function extractWindowNameFromClass(classNode: ts.ClassDeclaration): string | null {
  const decorators = ts.canHaveDecorators(classNode) ? ts.getDecorators(classNode) : undefined;
  if (!decorators) return null;

  const windowDecorator = decorators.find(decorator => {
    if (!ts.isCallExpression(decorator.expression)) return false;
    if (!decorator.expression.expression) return false;
    if (!ts.isIdentifier(decorator.expression.expression)) return false;
    return decorator.expression.expression.text === 'windowName';
  });

  if (!windowDecorator || !ts.isCallExpression(windowDecorator.expression)) return null;

  const windowNameArg = windowDecorator.expression.arguments[0];
  if (!windowNameArg || !ts.isStringLiteral(windowNameArg)) return null;

  return windowNameArg.text;
}

function extractHandlersFromClass(classNode: ts.ClassDeclaration): HandlerInfo[] {
  const handlers: HandlerInfo[] = [];

  classNode.members.forEach(member => {
    if (ts.isMethodDeclaration(member) && member.name && ts.isIdentifier(member.name)) {
      const decorators = ts.canHaveDecorators(member) ? ts.getDecorators(member) : undefined;
      if (!decorators) return;

      const handlerDecorator = decorators.find(decorator => {
        if (!ts.isCallExpression(decorator.expression)) return false;
        if (!decorator.expression.expression) return false;
        if (!ts.isIdentifier(decorator.expression.expression)) return false;
        return decorator.expression.expression.text === 'mainHandler';
      });

      if (handlerDecorator && ts.isCallExpression(handlerDecorator.expression)) {
        const handlerNameArg = handlerDecorator.expression.arguments[0];
        if (handlerNameArg && ts.isStringLiteral(handlerNameArg)) {
          const { parameterType, returnType } = extractMethodTypes(member);
          handlers.push({
            methodName: member.name.text,
            handlerName: handlerNameArg.text,
            hasResponseHandler: false, // TODO: detect response handlers
            parameterType,
            returnType
          });
        }
      }
    }
  });

  return handlers;
}

function extractMethodTypes(method: ts.MethodDeclaration): { parameterType: string; returnType: string } {
  let parameterType = 'void';
  let returnType = 'any';

  // Extract parameter type
  if (method.parameters && method.parameters.length > 0) {
    const firstParam = method.parameters[0];
    if (firstParam && firstParam.type) {
      parameterType = typeNodeToString(firstParam.type);
    }
  }

  // Extract return type from Promise<T>
  if (method.type) {
    const typeStr = typeNodeToString(method.type);
    // Match Promise<T> pattern
    const promiseMatch = typeStr.match(/^Promise<(.+)>$/);
    if (promiseMatch && promiseMatch[1]) {
      returnType = promiseMatch[1];
    } else {
      returnType = typeStr;
    }
  }

  return { parameterType, returnType };
}

function typeNodeToString(typeNode: ts.TypeNode): string {
  switch (typeNode.kind) {
    case ts.SyntaxKind.StringKeyword:
      return 'string';
    case ts.SyntaxKind.NumberKeyword:
      return 'number';
    case ts.SyntaxKind.BooleanKeyword:
      return 'boolean';
    case ts.SyntaxKind.VoidKeyword:
      return 'void';
    case ts.SyntaxKind.AnyKeyword:
      return 'any';
    case ts.SyntaxKind.TypeReference:
      const typeRef = typeNode as ts.TypeReferenceNode;
      if (ts.isIdentifier(typeRef.typeName)) {
        let typeName = typeRef.typeName.text;
        if (typeRef.typeArguments && typeRef.typeArguments.length > 0) {
          const args = typeRef.typeArguments.map(arg => typeNodeToString(arg)).join(', ');
          typeName += `<${args}>`;
        }
        return typeName;
      }
      break;
    case ts.SyntaxKind.TypeLiteral:
      const typeLiteral = typeNode as ts.TypeLiteralNode;
      const members = typeLiteral.members.map(member => {
        if (ts.isPropertySignature(member) && member.name && ts.isIdentifier(member.name)) {
          const propName = member.name.text;
          const propType = member.type ? typeNodeToString(member.type) : 'any';
          const optional = member.questionToken ? '?' : '';
          return `${propName}${optional}: ${propType}`;
        }
        return '';
      }).filter(Boolean);
      return `{ ${members.join('; ')} }`;
    case ts.SyntaxKind.ArrayType:
      const arrayType = typeNode as ts.ArrayTypeNode;
      return `${typeNodeToString(arrayType.elementType)}[]`;
    case ts.SyntaxKind.UnionType:
      const unionType = typeNode as ts.UnionTypeNode;
      return unionType.types.map(t => typeNodeToString(t)).join(' | ');
    case ts.SyntaxKind.LiteralType:
      const literalType = typeNode as ts.LiteralTypeNode;
      if (ts.isStringLiteral(literalType.literal)) {
        return `"${literalType.literal.text}"`;
      }
      if (ts.isNumericLiteral(literalType.literal)) {
        return literalType.literal.text;
      }
      return 'any';
    case ts.SyntaxKind.TupleType:
      const tupleType = typeNode as ts.TupleTypeNode;
      const tupleElements = tupleType.elements.map(e => typeNodeToString(e)).join(', ');
      return `[${tupleElements}]`;
    case ts.SyntaxKind.ParenthesizedType:
      const parenType = typeNode as ts.ParenthesizedTypeNode;
      return `(${typeNodeToString(parenType.type)})`;
    case ts.SyntaxKind.FunctionType:
      return 'Function';
  }

  // Fallback: use printer to get the text representation safely
  try {
    const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
    const result = printer.printNode(ts.EmitHint.Unspecified, typeNode, typeNode.getSourceFile());
    return result || 'any';
  } catch {
    return 'any';
  }
}

/**
 * Collect all custom type references from a type string
 */
function collectTypeReferences(typeStr: string, collected: Set<string>): void {
  // Match type names (capitalized identifiers that aren't built-in)
  const typePattern = /\b([A-Z][a-zA-Z0-9]*)\b/g;
  let match;
  while ((match = typePattern.exec(typeStr)) !== null) {
    const typeName = match[1];
    if (!BUILTIN_TYPES.has(typeName)) {
      collected.add(typeName);
    }
  }
}

/**
 * Extract interface/type definitions from source files
 */
function extractInterfaceDefinitions(
  program: ts.Program,
  projectRoot: string,
  typeNames: Set<string>
): Map<string, string> {
  const definitions = new Map<string, string>();

  if (typeNames.size === 0) return definitions;

  const sourceFiles = program.getSourceFiles().filter(
    file => !file.fileName.includes('node_modules') &&
            !file.fileName.includes('.d.ts') &&
            file.fileName.includes(projectRoot)
  );

  for (const sourceFile of sourceFiles) {
    ts.forEachChild(sourceFile, node => {
      // Handle interface declarations
      if (ts.isInterfaceDeclaration(node) && node.name) {
        const name = node.name.text;
        if (typeNames.has(name) && !definitions.has(name)) {
          definitions.set(name, interfaceToString(node, sourceFile));
        }
      }
      // Handle type alias declarations
      if (ts.isTypeAliasDeclaration(node) && node.name) {
        const name = node.name.text;
        if (typeNames.has(name) && !definitions.has(name)) {
          definitions.set(name, typeAliasToString(node, sourceFile));
        }
      }
    });
  }

  return definitions;
}

/**
 * Convert an interface declaration to a string
 */
function interfaceToString(node: ts.InterfaceDeclaration, sourceFile: ts.SourceFile): string {
  const name = node.name.text;
  const members: string[] = [];

  for (const member of node.members) {
    if (ts.isPropertySignature(member) && member.name) {
      const propName = ts.isIdentifier(member.name) ? member.name.text : member.name.getText(sourceFile);
      const optional = member.questionToken ? '?' : '';
      const propType = member.type ? typeNodeToString(member.type) : 'any';
      members.push(`  ${propName}${optional}: ${propType};`);
    }
  }

  return `interface ${name} {\n${members.join('\n')}\n}`;
}

/**
 * Convert a type alias declaration to a string
 */
function typeAliasToString(node: ts.TypeAliasDeclaration, sourceFile: ts.SourceFile): string {
  const name = node.name.text;
  const typeStr = typeNodeToString(node.type);
  return `type ${name} = ${typeStr};`;
}