// Auto-generated IPC types
// Do not edit this file manually - run 'tronbun generate-types' to regenerate

// Extracted type definitions
interface FileEntry {
  name: string;
  path: string;
  isDirectory: boolean;
  size: number;
  modified: string;
}

interface ChatMessage {
  role: "user" | "assistant" | "system";
  content: string;
}

interface Model {
  id: string;
  name: string;
}

// Generated handlers for CoworkWindow
export interface CoworkWindowHandlers {
  setApiKey: (data: string) => Promise<void>;
  getApiKey: (data: void) => Promise<string>;
  getModels: (data: void) => Promise<Model[]>;
  setModel: (data: string) => Promise<void>;
  getSelectedModel: (data: void) => Promise<string>;
  selectFolder: (data: string) => Promise<{ success: boolean; path: string }>;
  getWorkingDirectory: (data: void) => Promise<string>;
  getHomeDirectory: (data: void) => Promise<string>;
  listFiles: (data: string) => Promise<FileEntry[]>;
  readFile: (data: string) => Promise<{ success: boolean; content: string; error?: string }>;
  writeFile: (data: string) => Promise<{ success: boolean; error?: string }>;
  createFile: (data: string) => Promise<{ success: boolean; path: string; error?: string }>;
  createFolder: (data: string) => Promise<{ success: boolean; path: string; error?: string }>;
  deleteFile: (data: string) => Promise<{ success: boolean; error?: string }>;
  getRelativePath: (data: string) => Promise<string>;
  sendMessage: (data: string) => Promise<{ success: boolean; response: string; error?: string }>;
  clearChat: (data: void) => Promise<void>;
  hasPendingPlan: (data: void) => Promise<boolean>;
  cancelPlan: (data: void) => Promise<void>;
  getChatHistory: (data: void) => Promise<ChatMessage[]>;
}


declare global {
  interface Window {
    cowork: CoworkWindowHandlers;
  }
}
